# Generated by Django 4.1.6 on 2023-04-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_district_alter_customuser_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='district_id_no',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state_id_no',
        ),
    ]
