# Generated by Django 4.1.6 on 2023-04-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Phone_Number',
            field=models.IntegerField(),
        ),
    ]
