# Generated by Django 4.1.6 on 2023-04-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rank_master_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank_master',
            name='rank_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
