# Generated by Django 4.1.6 on 2023-04-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_rank_master_rank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police_incharge',
            name='incharge_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
