# Generated by Django 4.1.6 on 2023-05-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_police_police_officer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='police_incharge',
        ),
    ]
