# Generated by Django 4.1.7 on 2023-05-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_police_incharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='Profile images/default.png', null=True, upload_to='Profile images/'),
        ),
    ]
