# Generated by Django 4.1.6 on 2023-05-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0026_complaint_master_info_by_station_incharge'),
        ('accounts', '0028_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='police_officer',
            name='station_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='complaints.police_station_master'),
        ),
    ]
