# Generated by Django 4.1.6 on 2023-04-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crime_category_master',
            fields=[
                ('crime_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('crime_category_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='district_master',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=150, unique=True)),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('status_id', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='state_master',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=150, unique=True)),
                ('status_id', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='police_station_master',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=150, unique=True)),
                ('station_mail', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('address', models.TextField(max_length=150)),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('district_id', models.IntegerField(blank=True, null=True)),
                ('pin_code', models.IntegerField()),
                ('status_id', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('district_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.district_master', to_field='district_name')),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.state_master', to_field='state_name')),
            ],
        ),
        migrations.AddField(
            model_name='district_master',
            name='state_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.state_master', to_field='state_name'),
        ),
        migrations.CreateModel(
            name='complaint_master',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complainant_name', models.CharField(max_length=150)),
                ('complainant_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('complainant_contact_no', models.IntegerField()),
                ('complainant_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('complainant_dob', models.DateField()),
                ('complainant_address', models.TextField()),
                ('complainant_state_id', models.IntegerField(blank=True, null=True)),
                ('complainant_district_id', models.IntegerField(blank=True, null=True)),
                ('complainant_pin_code', models.IntegerField()),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('district_id', models.IntegerField(blank=True, null=True)),
                ('station_id', models.IntegerField(blank=True, null=True)),
                ('status_id', models.CharField(choices=[('Pending', 'Pending'), ('CSR is filed', 'CSR is filed'), ('FIR is filed', 'FIR is filed'), ('Rejected', 'Rejected')], max_length=15)),
                ('other_crime_category', models.CharField(blank=True, max_length=150, null=True)),
                ('subject', models.CharField(max_length=150)),
                ('detailed_description', models.TextField(max_length=10000)),
                ('delay_reason', models.TextField(max_length=1000)),
                ('datetime_of_occurence', models.DateTimeField()),
                ('place_of_occurence', models.CharField(blank=True, max_length=150, null=True)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='complaint images/')),
                ('complainant_district_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="complainant's_district+", to='complaints.district_master', to_field='district_name')),
                ('complainant_state_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="complainant's_state+", to='complaints.state_master', to_field='state_name')),
                ('crime_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.crime_category_master', to_field='crime_category_name')),
                ('district_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_in_district+', to='complaints.district_master', to_field='district_name')),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_in_state+', to='complaints.state_master', to_field='state_name')),
                ('station_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="complainant's_district+", to='complaints.police_station_master', to_field='station_name')),
            ],
        ),
    ]
