# Generated by Django 4.1.6 on 2023-04-28 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_master_evidence_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint_master',
            options={'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterModelOptions(
            name='crime_category_master',
            options={'verbose_name_plural': 'Crime Categories'},
        ),
        migrations.AlterModelOptions(
            name='district_master',
            options={'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='police_station_master',
            options={'verbose_name_plural': 'Police Stations'},
        ),
        migrations.AlterModelOptions(
            name='state_master',
            options={'verbose_name_plural': 'States'},
        ),
        migrations.AlterField(
            model_name='complaint_master',
            name='complainant_district_name',
            field=models.ForeignKey(limit_choices_to={'state_name': models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="complainant's_state+", to='complaints.state_master', to_field='state_name')}, on_delete=django.db.models.deletion.PROTECT, related_name="complainant's_district+", to='complaints.district_master', to_field='district_name'),
        ),
        migrations.AlterField(
            model_name='complaint_master',
            name='complaint_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='complaint_master',
            name='district_name',
            field=models.ForeignKey(limit_choices_to={'state_name': models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_in_state+', to='complaints.state_master', to_field='state_name')}, on_delete=django.db.models.deletion.PROTECT, related_name='complaint_in_district+', to='complaints.district_master', to_field='district_name'),
        ),
        migrations.AlterField(
            model_name='complaint_master',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint images/'),
        ),
        migrations.AlterField(
            model_name='complaint_master',
            name='station_name',
            field=models.ForeignKey(limit_choices_to={'district_name': models.ForeignKey(limit_choices_to={'state_name': models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_in_state+', to='complaints.state_master', to_field='state_name')}, on_delete=django.db.models.deletion.PROTECT, related_name='complaint_in_district+', to='complaints.district_master', to_field='district_name')}, on_delete=django.db.models.deletion.PROTECT, related_name='complainant_in_police_station+', to='complaints.police_station_master', to_field='station_name'),
        ),
        migrations.AlterField(
            model_name='crime_category_master',
            name='crime_category_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='district_master',
            name='district_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='police_station_master',
            name='district_name',
            field=models.ForeignKey(limit_choices_to={'state_name': models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.state_master', to_field='state_name')}, on_delete=django.db.models.deletion.PROTECT, to='complaints.district_master', to_field='district_name'),
        ),
        migrations.AlterField(
            model_name='police_station_master',
            name='station_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='police_station_master',
            name='station_mail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='state_master',
            name='state_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
