# Generated by Django 4.1.6 on 2023-04-28 07:18

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_master_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police_station_master',
            name='district_name',
            field=models.ForeignKey(limit_choices_to={'state_name_id': django.db.models.expressions.OuterRef('state_name_id')}, on_delete=django.db.models.deletion.PROTECT, to='complaints.district_master', to_field='district_name'),
        ),
    ]
