# Generated by Django 4.1.6 on 2023-04-28 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_alter_complaint_master_station_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_master',
            name='complainant_district_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="complainant's_district+", to='complaints.district_master', to_field='district_name'),
        ),
        migrations.AlterField(
            model_name='complaint_master',
            name='district_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_in_district+', to='complaints.district_master', to_field='district_name'),
        ),
        migrations.AlterField(
            model_name='complaint_master',
            name='station_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complainant_in_police_station+', to='complaints.police_station_master', to_field='station_name'),
        ),
        migrations.AlterField(
            model_name='police_station_master',
            name='district_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.district_master', to_field='district_name'),
        ),
    ]
