# Generated by Django 4.1.6 on 2023-04-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_alter_complaint_master_complainant_district_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state_master',
            options={'verbose_name_plural': 'States and Union Territories'},
        ),
    ]
