# Generated by Django 4.1.6 on 2023-04-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_alter_state_master_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_master',
            name='delay_reason',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
