# Generated by Django 4.1.6 on 2023-04-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_complaint_master_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint_master',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
