# Generated by Django 4.1.6 on 2023-04-28 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_complaint_master_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime_category_master',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
