# Generated by Django 4.1.6 on 2023-04-28 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_alter_crime_category_master_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_master',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='complaint_master',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
