# Generated by Django 4.1.6 on 2023-04-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_alter_complaint_master_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='police_station_master',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
