# Generated by Django 4.1.6 on 2023-04-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_alter_police_station_master_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_master',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
