# Generated by Django 4.1.7 on 2023-04-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0014_alter_complaint_master_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_master',
            name='status_id',
            field=models.CharField(choices=[('Pending', 'Pending'), ('CSR is filed', 'CSR is filed'), ('FIR is filed', 'FIR is filed'), ('Rejected', 'Rejected')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='police_station_master',
            name='station_mail',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
    ]
