# Generated by Django 4.1.6 on 2023-05-01 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0017_rename_detailed_description_csr_master_ncr_detailed_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csr_master',
            name='info_by_station_incharge',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='complaint_master',
            name='subject',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='csr_master',
            name='subject',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='fir_master',
            fields=[
                ('fir_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fir_no', models.CharField(max_length=150, unique=True)),
                ('complainant_name', models.CharField(max_length=150)),
                ('complainant_gender', models.CharField(max_length=6)),
                ('complainant_contact_no', models.IntegerField()),
                ('complainant_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('complainant_dob', models.DateField()),
                ('complainant_address', models.TextField()),
                ('complainant_state_id', models.IntegerField(blank=True, null=True)),
                ('complainant_district_id', models.IntegerField(blank=True, null=True)),
                ('complainant_pin_code', models.IntegerField()),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('district_id', models.IntegerField(blank=True, null=True)),
                ('station_id', models.IntegerField(blank=True, null=True)),
                ('status_id', models.CharField(choices=[('FIR in progress', 'FIR in progress'), ('Completed', 'Completed')], default='FIR in progress', max_length=20)),
                ('other_crime_category', models.CharField(blank=True, max_length=150, null=True)),
                ('subject', models.CharField(max_length=500)),
                ('fir_detailed_description', models.TextField(max_length=10000)),
                ('delay_reason', models.TextField(blank=True, max_length=1000, null=True)),
                ('datetime_of_occurence', models.DateTimeField()),
                ('place_of_occurence', models.CharField(blank=True, max_length=150, null=True)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='complaint images/')),
                ('act_and_sections', models.CharField(max_length=500)),
                ('type_of_information', models.CharField(choices=[('Oral', 'Oral'), ('Written', 'Written')], max_length=20)),
                ('nearest_identifiable_place', models.CharField(max_length=500)),
                ('direction_and_distance_from_ps', models.CharField(max_length=500)),
                ('complaintant_religion', models.CharField(max_length=500)),
                ('complaintant_caste', models.CharField(max_length=500)),
                ('sus_acu_details', models.TextField(max_length=500)),
                ('properties_involved', models.TextField(max_length=500)),
                ('property_value', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('complainant_district_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="complainant's_district+", to='complaints.district_master', to_field='district_name')),
                ('complainant_state_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="complainant's_state+", to='complaints.state_master', to_field='state_name')),
                ('crime_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.crime_category_master', to_field='crime_category_name')),
                ('district_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_in_district+', to='complaints.district_master', to_field='district_name')),
                ('state_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_in_state+', to='complaints.state_master', to_field='state_name')),
                ('station_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complainant_in_police_station+', to='complaints.police_station_master', to_field='station_name')),
            ],
            options={
                'verbose_name_plural': 'FIRs',
            },
        ),
    ]
