# Generated by Django 4.1.6 on 2023-05-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0018_csr_master_info_by_station_incharge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_master',
            name='status_id',
        ),
        migrations.AddField(
            model_name='complaint_master',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('CSR Filed', 'CSR is Filed'), ('FIR Filed', 'FIR is Filed'), ('Rejected', 'Rejected')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='csr_master',
            name='status_id',
            field=models.CharField(choices=[('CSR Filed', 'CSR is Filed'), ('Completed', 'Completed')], default='CSR in progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='fir_master',
            name='status_id',
            field=models.CharField(choices=[('FIR Filed', 'FIR is Filed'), ('Completed', 'Completed')], default='FIR in progress', max_length=20),
        ),
    ]
