# Generated by Django 4.1.6 on 2023-05-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0019_remove_complaint_master_status_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir_master',
            name='info_by_station_incharge',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='complaint_master',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('CSR is Filed', 'CSR is Filed'), ('FIR is Filed', 'FIR is Filed'), ('Rejected', 'Rejected')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='csr_master',
            name='status_id',
            field=models.CharField(choices=[('CSR is Filed', 'CSR is Filed'), ('Completed', 'Completed')], default='CSR in progress', max_length=20),
        ),
    ]
