# Generated by Django 4.1.6 on 2023-05-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0020_fir_master_info_by_station_incharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir_master',
            name='gd_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
