# Generated by Django 4.1.6 on 2023-05-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0021_fir_master_gd_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fir_master',
            old_name='status_id',
            new_name='status',
        ),
    ]
