# Generated by Django 4.1.6 on 2023-05-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0026_complaint_master_info_by_station_incharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='csr_master',
            name='feedback',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fir_master',
            name='feedback',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
